name: Terraform CI/CD

on:
  push:
    branches: [main]
    paths: ['infra/**']          # adjust to your layout
  pull_request:
    paths: ['infra/**']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write          # lets reviewdog annotate PRs

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_WORKING_DIR: infra         # single place to tweak later

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183969845:role/github-assume-role
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_cache: true

      - name: Init
        run: terraform init -input=false

      - name: Format
        run: terraform fmt -check -diff -recursive

      - name: Validate
        run: terraform validate

      - name: TFLint
        uses: reviewdog/action-tflint@v1
        with:
          working-directory: ${{ env.TF_WORKING_DIR }}
          reporter: github-pr-review

      - name: Plan
        run: terraform plan -no-color -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: prod           # requires manual approval
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183969845:role/github-assume-role
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_cache: true

      - name: Apply
        run: terraform apply -auto-approve -no-color tfplan
